version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Booking: The Booking microservice
  ###################################
  booking:
    build:
      context: ./
      dockerfile: booking.Dockerfile
    image: booking:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/booking
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"


    ###################################
  # Review: The Review microservice
  ###################################
  review:
    build:
      context: ./
      dockerfile: review.Dockerfile
    image: review:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/review
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"



 
  #######################################################
  # Shipping Record: The Shipping Record microservice
  #######################################################
  customer:
    build:
      context: ./
      dockerfile: customer.Dockerfile
    image: customer:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/customer
      PYTHONUNBUFFERED: 1
    ports: 
      - "5003:5003"
  #######################################################
  # Paypal Record: The paypal Record microservice
  #######################################################
  payment:
    build:
      context: ./
      dockerfile: payment.Dockerfile
    image: payment:latest
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports: 
      - "5006:5006"

  webhook:
    build:
      context: ./
      dockerfile: webhook.Dockerfile
    image: webhook:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports: 
      - "5010:5010"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  get_booking_details:
    build:
      context: ./
      dockerfile: get_booking_details.Dockerfile
    image: get_booking_details:latest
    restart: always
    depends_on:
      # - activity
      - customer
      - activity
      - payment
      # - booking_log
      # - error
      # - rabbitmq
    environment:
      activity_URL: http://activity:5001/activity
      customer_URL: http://customer:5003/customer
      # shipping_record_URL: http://shipping_record:5002/shipping_record 
      PYTHONUNBUFFERED: 1
    ports:
      - "5012:5012"

  get_coupons:
    build:
      context: ./
      dockerfile: get_coupons.Dockerfile
    image: get_coupons:latest
    restart: always
    depends_on:
      # - activity
      - coupon
      - customer
      # - booking_log
      # - error
      # - rabbitmq
    environment:
      activity_URL: http://coupon:5013/coupon
      customer_URL: http://customer:5003/customer
      # shipping_record_URL: http://shipping_record:5002/shipping_record 
      PYTHONUNBUFFERED: 1
    ports:
      - "5014:5014"
  ##################################
  # Activity: The ACtivity microservice
  ##################################
  activity:
    build:
      context: ./
      dockerfile: activity.Dockerfile
    image: activity:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/activity
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  coupon:
    build:
      context: ./
      dockerfile: coupon.Dockerfile
    image: coupon:latest
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/coupon
      PYTHONUNBUFFERED: 1
    ports:
      - "5013:5013"

  ##################################
  # Send Email: The email notification microservice
  ##################################
  send_email:
    build:
      context: ./
      dockerfile: send_email.Dockerfile
    image: send_email:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: "http://booking:5002/booking"
      customer_URL: "http://localhost:5003/customer"
      activity_URL: "http://127.0.0.1:5001/activity"
      PYTHONUNBUFFERED: 1
    ports:
      - "5020:5020"

  send_redeem_email:
    build:
      context: ./
      dockerfile: send_redeem_email.Dockerfile
    image: send_redeem_email:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: "http://booking:5002/booking"
      customer_URL: "http://localhost:5003/customer"
      activity_URL: "http://127.0.0.1:5001/activity"
      PYTHONUNBUFFERED: 1
    ports:
      - "5022:5022"


  ##################################
  # stripe
  ##################################
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key rk_test_51Miv0mDVT8kjXSeFW0WFB8fY9s54w4eSn7QJDYFgXiMCKdVH08eTQZfApoOwI261KyLrrhVIlq4hFUUaadX9npkf00ov0KzqBs --forward-to webhook:5010/webhook"


  ##################################
  # Recommender
  ##################################
  recommender:
    build:
      context: ./
      dockerfile: recommender.Dockerfile
    image: recommender:latest
    restart: always
    environment:
      activity_URL: "http://127.0.0.1:5001/activity"
      review_URL: "http://127.0.0.1:5004/review"
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ##################################
  # verify_booking
  ##################################
  verify_booking:
    build:
      context: ./
      dockerfile: verify_booking.Dockerfile
    image: verify_booking:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: "http://localhost:5002/booking"
      send_email_URL: "http://127.0.0.1:5020/send_email"
      pendingReview_URL: "http://localhost:5004/pendingReview"
      PYTHONUNBUFFERED: 1
    ports:
      - "5030:5030"

    # add_review:
    #   build:
    #     context: ./
    #     dockerfile: add_review.Dockerfile
    #   image: add_review:latest
    #   restart: always
    #   environment:
    #     customer_URL: "http://localhost:5003/customer/"
    #     review_URL: "http://localhost:5004/"
    #     PYTHONUNBUFFERED: 1
    #   ports:
    #     - "5150:5150"
  